[workspace]
members = [
    "fibo",
    "new_struct",
    "shadowing",
    "function",
    "data_type", "ownership", "lifetime", "double_linked_list", "adder", "calc", "view", "generic_Type", "unrecoverable_error",
]
