[package]
name = "learn_mutex"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.42.0", features=["full"]}
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.134"
sqlite = "0.36.1"